version: '3'
services:
  frontend:
    image: nginx:1.15.7
    volumes:
      - ./front-end-app:/usr/share/nginx/html/
    ports:
      - 80:80
    depends_on:
      - backend
  backend:
    build: ./back-end-bridge-ws/
    command: npm start
    volumes:
      - ./back-end-bridge-ws:/usr/src/app
      - /usr/app/node_modules
    ports:
      - 8887:8887
    environment:
      - NODE_ENV="development"